version: "3.5"

volumes:
    wp:
        driver: local
        driver_opts:
            type:
                none
            device: /home/aribesni/data/wp
            o: bind
    db:
        driver: local
        driver_opts:
            type:
                none
            device: /home/aribesni/data/db
            o: bind

networks:
    inception:
        driver: bridge

services:
    mariadb:
        container_name: mariadb
        env_file:
            - .env
        build:
            context: requirements/mariadb/
              #args:
              # _DB_ADMIN_LOGIN: ${_DB_ADMIN_LOGIN}
              # _DB_ADMIN_PASSWD: ${_DB_ADMIN_PASSWD}
              # _DB_ROOT_PASSWD: ${_DB_ROOT_PASSWD}
        networks:
            - inception
        volumes:
            - db:/var/lib/mysql
        restart: unless-stopped

    wordpress:
        container_name: wordpress
        build:
            context: requirements/wordpress/
              #args:
              # _DB_ADMIN_LOGIN: ${_DB_ADMIN_LOGIN}
              # _DB_ADMIN_PASSWD: ${_DB_ADMIN_PASSWD}
        networks:
            - inception
        volumes:
            - wp:/var/www/html
        env_file:
            - .env
        restart: unless-stopped
        depends_on:
            - mariadb
    nginx:
        container_name: nginx
        build: requirements/nginx
        ports:
            - "443:443"
        networks:
            - inception
        volumes:
            - wp:/var/www/html
        env_file:
            - .env
        restart: unless-stopped
        depends_on:
            - wordpress
