# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    docker-compose.yml                                 :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: aribesni <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/11/04 13:07:48 by aribesni          #+#    #+#              #
#    Updated: 2022/11/04 13:07:50 by aribesni         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

version: '3.9'

services:
  mariadb:
    image: mariadb
    container_name: mariadb
    networks:
      - inception
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - mariadb:/var/lib/mysql
    restart: on-failure
    expose:
      - "3306"

  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    depends_on:
      - wordpress
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "4430:4430"
    restart: on-failure
  
  wordpress:
    image: wordpress
    container_name: wordpress
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - mariadb
    restart: on-failure
    expose:
      - "9000"

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/host_mnt/Users/aristidebesnier/Documents/42/Inception/volumes/wordpress'
  mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/host_mnt/Users/aristidebesnier/Documents/42/Inception/volumes/mariadb'

networks:
  inception:
    driver: bridge