
CREATE DATABASE IF NOT EXISTS wordpress;
CREATE USER IF NOT EXISTS '$DB_ADMIN_LOGIN'@'%' IDENTIFIED BY '$DB_ADMIN_PASSWD';
GRANT ALL PRIVILEGES ON wordpress.* TO '$DB_ADMIN_LOGIN'@'%';
ALTER USER 'root'@'localhost' IDENTIFIED BY '$DB_ROOT_PASSWD';